openapi: 3.0.1
info:
  title: Dodo IS API
  version: '1.0'
  contact:
    email: support@dodopizza.com
    name: Dodo Brands
    url: 'https://dodobrands.io/'
  termsOfService: 'https://cdn.dodostatic.net/files/docs/saas_dodopizzaru_ru.pdf'
  license:
    url: 'https://cdn.dodostatic.net/files/docs/saas_dodopizzaru_ru.pdf'
    name: Custom
servers:
  - url: 'https://api.dodois.io/dodopizza/ru'
    description: Россия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ae'
    description: ОАЭ — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/am'
    description: Армения — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/az'
    description: Азербайджан — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/bg'
    description: Болгария — Dodopizza
  - url: 'https://api.dodois.io/dodopizza/by'
    description: Беларусь — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/cy'
    description: Кипр — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/de'
    description: Германия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ee'
    description: Эстония — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/es'
    description: Испания — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/gb'
    description: Великобритания — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ge'
    description: Грузия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/hr'
    description: Хорватия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/hu'
    description: Венгрия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/id'
    description: Индонезия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/iq'
    description: Ирак — Dodopizza
  - url: 'https://api.dodois.io/dodopizza/kg'
    description: Киргизия — Dodopizza
  - url: 'https://api.dodois.io/dodopizza/kz'
    description: Казахстан — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/lt'
    description: Литва — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ma'
    description: Марокко — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/md'
    description: Молдова — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/me'
    description: Черногория — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/mn'
    description: Монголия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/mx'
    description: Мексика — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ng'
    description: Нигерия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/pl'
    description: Польша — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/qa'
    description: Катар — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/ro'
    description: Румыния — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/rs'
    description: Сербия — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/si'
    description: Словения — Dodopizza
  - url: 'https://api.dodois.io/dodopizza/tj'
    description: Таджикистан — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/tr'
    description: Турция — Dodopizza
  - url: 'https://api.dodois.io/dodopizza/uz'
    description: Узбекистан — Dodopizza
  - url: 'https://api.dodois.com/dodopizza/vn'
    description: Вьетнам — Dodopizza
  - url: 'https://api.dodois.com/drinkit/ae'
    description: ОАЭ — Drinkit
  - url: 'https://api.dodois.com/drinkit/az'
    description: Азербайджан — Drinkit
  - url: 'https://api.dodois.io/drinkit/kz'
    description: Казахстан — Drinkit
  - url: 'https://api.dodois.io/drinkit/ru'
    description: Россия — Drinkit
  - url: 'https://api.dodois.com/drinkit/us'
    description: США — Drinkit
paths:
  /production/orders-handover-time:
    get:
      summary: Производство → Время выдачи заказа
      operationId: get-production-ordershandovertime
      description: |-
        Возвращает время выдачи заказов за выбранный период по пиццериям (`units`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        ### Округление до целых секунд:
        Длительность событий (например, `cookingTime`) представлена целыми числами и округляется до целых секунд.
        0.5 и больше секунд округляется вверх, 0.4 и меньше - вниз.

        ### Исключенные данные:
        Напитки и неприготовляемые продукты исключаются из выборки.
        В расчет не попадают заказы с временем приготовления выпекаемых продуктов меньше 1 минуты, заказы без выпекаемых продуктов (кусочки, напитки, фонданы и т.д.) и заказы с временем выдачи больше 1 часа.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      x-internal: false
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
      tags:
        - Производство
  /orders/clients-statistics:
    get:
      summary: Заказы → Статистика по новым клиентам
      operationId: get-orders-client-statistics
      description: |-
        Получение статистики по клиентам в заведении.
        Возвращает информацию о новых клиентах в заведении и на достаку.
        Так же информацию о старых клиентах.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `fromDate` должен быть меньше или равен `toDate`.
        4. Максимальный период запроса - 31 день

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >    
        >   `Shift supervisor` - Менеджер смены
      x-internal: false
      security:
        - Authorization:
            - orders
            - 'user.role:read'
      tags:
        - Заказы
  /production/tracking-metrics/summary:
    get:
      summary: Производство → Метрики с трекинга (Сводные)
      description: |-
        Позволяет получить сводную информацию о времени, проведенном продуктом на различных станциях производства за указанный период.

        При запросе за определенный период (`from`, `to`) и запросе по нескольким заведениям (`units`), будет возвращено среднее значение по каждому продукту за весь интервал from to отдельно для каждого заведения.

        ### Требования к query параметрам: 
        1. В `units` можно передать 1 заведение;
        3. В `products` можно перечислить до 30 продуктов в одном запросе; 
        4. В `products` следует перечислять UUID-ы строго через запятую без пробелов; 
        5. Диапазон дат между `toDate` и `fromDate` параметрами не должен превышать 7 деней.
        6. В ответе будет отображаться информация за период `fromDate`-`toDate` включительно `fromDate`.
        7. Если нужно получить данные за один день укажите `fromDate` = `toDate`.

        >#### Доступно для следующих ролей: 
        >   `Division administrator` - Администратор подразделения 
        >
        >   `Store Manager` - Менеджер офиса 
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
      operationId: get-production-tracking-metrics-summary
      tags:
        - Производство
  /production/orders-handover-statistics:
    get:
      summary: Производство → Статистика выдачи заказов
      operationId: get-production-orders-handover-time-statistics
      description: |-
        Возвращает агрегированные данные по выдаче заказов за выбранный период по пиццериям (`units`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        1. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        1. В `salesChannels` следует перечислять каналы продаж (Delivery,DineIn,TakeAway) строго через запятую без пробелов;
        1. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        ### Округление до целых секунд:
        Длительность событий (например, `avgCookingTime`) представлена целыми числами и округляется до целых секунд.
        0.5 и больше секунд округляется вверх, 0.4 и меньше - вниз.

        ### Исключенные данные:
        Напитки и неприготовляемые продукты исключаются из выборки.
        В расчет не попадают заказы с временем приготовления выпекаемых продуктов меньше 1 минуты, заказы без выпекаемых продуктов (кусочки, напитки, фонданы и т.д.) и заказы с временем выдачи больше 1 часа.
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
      tags:
        - Производство
  /production/productivity:
    get:
      summary: Производство → Производительность
      operationId: get-staff-productivity
      description: |-
        Возвращает метрики производительности за выбранный период и указанным пиццериям (`units`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        1. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        1. Диапазон дат между `from` и `to` параметрами не должен превышать 31 день;
        1. Даты `from` и `to` должны быть округлены до часов.


        Как расчитывается показатель «Скорость»

        Скорость — процент продуктов, изготовленных быстрее установленного стандартного времени. Для расчета скорости количество продуктов, приготовленных вовремя за период, делится на общее количество продуктов за этот период.<br />
        ⚠️ Скорость за день не считается, как средняя скоростей за смены.

        *Смена 1: вовремя приготовили 10 продуктов, всего — 100. Скорость за смену 10 / 100 = 10%.*<br />
        *Смена 2: вовремя приготовили 50 продуктов, всего — 150. Скорость за смену 50 /150 = 30%.*<br />
        *Показатель скорость будет = (10 + 50) / (100 + 150) = 24. Если вы посчитаете среднее по сменам, то результат будет некорректный (10 + 30) / 2 = 20.*

        **Важное замечание:** Не учитываются отмененные заказы (State != 12)
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
      tags:
        - Производство
  /production/stop-sales-channels:
    get:
      summary: Производство → Стоп-продажи по каналам продаж
      operationId: get-production-stop-sales-saleschannels
      description: |-
        Возвращает данные о стопах продаж за период для набора пиццерий (`units`).
        Стопы сгруппированы по пиццериям и каналам продаж: доставка, самовывоз, ресторан.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - stopsales
            - 'user.role:read'
      tags:
        - Производство
  /production/stop-sales-ingredients:
    get:
      summary: Производство → Стоп-продажи по ингредиентам
      operationId: get-production-stop-sales-statistics-ingredients
      description: |-
        Возвращает данные о стопах продаж за период для набора пиццерий (`units`).
        Стопы сгруппированы по пиццериям и ингридиентам.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - stopsales
            - 'user.role:read'
      tags:
        - Производство
  /production/stop-sales-products:
    get:
      summary: Производство → Стоп-продажи по продуктам
      operationId: get-production-stop-sales-statistics-products
      description: |-
        Возвращает данные о стопах продаж за период для набора пиццерий (`units`).
        Стопы сгруппированы по пиццериям и продуктам.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - stopsales
            - 'user.role:read'
      tags:
        - Производство
  /production/unit-workload-by-orders:
    get:
      summary: Производство → Нагрузка на заведение по заказам
      operationId: get-production-unit-workload-by-orders
      description: |-
        Позволяет получить нагрузку по заказам на заведение за период в разрезе часа.

        В ответе будут включены только те промежутки, в которых производились заказы по заданному фильтру. Так например если заведение работает с 09:00 - 23:00, то в ответе будут только промежутки между 09:00 - 23:00. Любой отсутствующий промежуток можно считать за 0.

        ### Исключенные данные:
        Из выборки исключаются следующие данные:
          - Заказы со статусами отмененные и возвращенные заказы
          - Заказы типа "питание команды"
          - Бракованные продукты в заказах

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `toDate` и `fromDate` параметрами не должен превышать 14 деней;
        4. Временная часть (часы:минуты:секунды) в параметре `toDate` игнорируется. К дате из параметра `toDate` автоматически добавляется 1 день для формирования периода.
        Это гарантирует, что все данные за конечную дату включены в результаты.

        > Примеры:
        >
        >   При запросе с `'fromDate': '2025-06-16T00:00:00', 'toDate': '2025-06-16T23:59:59'` ->
        >   Фактически обрабатывается период: `2025-06-16 00:00:00` - `2025-06-17 00:00:00` (добавляется +1 день к toDate)
        > 
        >   При запросе с `'fromDate': '2025-06-16T00:00:00', 'toDate': '2025-06-17T00:00:00'` ->
        >   Фактически обрабатывается период: `2025-06-16 00:00:00` - `2025-06-18 00:00:00`
        5. В `products` можно перечислить до 30 заведений в одном запросе;
        6. В `products` следует перечислять UUID-ы строго через запятую без пробелов;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Производство
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
  /production/unit-workload-by-products:
    get:
      summary: Производство → Нагрузка на заведение по продуктам
      operationId: get-production-unit-workload-by-products
      description: |-
        Позволяет получить нагрузку по продуктам на заведение за период в разрезе часа.

        В ответе будут включены только те промежутки, в которых производились заказы по заданному фильтру. Так например если заведение работает с 09:00 - 23:00, то в ответе будут только промежутки между 09:00 - 23:00. Любой отсутствующий промежуток можно считать за 0.

        ### Исключенные данные:
        Из выборки исключаются следующие данные:
        - Заказы со статусами отмененные и возвращенные заказы
        - Заказы типа "питание команды"
        - Бракованные продукты в заказах

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `toDate` и `fromDate` параметрами не должен превышать 14 деней.
        4. Временная часть (часы:минуты:секунды) в параметре `toDate` игнорируется. К дате из параметра `toDate` автоматически добавляется 1 день для формирования периода.
        Это гарантирует, что все данные за конечную дату включены в результаты.

        > Примеры:
        >
        >   При запросе с `'fromDate': '2025-06-16T00:00:00', 'toDate': '2025-06-16T23:59:59'` ->
        >   Фактически обрабатывается период: `2025-06-16 00:00:00` - `2025-06-17 00:00:00` (добавляется +1 день к toDate)
        > 
        >   При запросе с `'fromDate': '2025-06-16T00:00:00', 'toDate': '2025-06-17T00:00:00'` ->
        >   Фактически обрабатывается период: `2025-06-16 00:00:00` - `2025-06-18 00:00:00`
        5. В `products` можно перечислить до 30 заведений в одном запросе;
        6. В `products` следует перечислять UUID-ы строго через запятую без пробелов;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Производство
      security:
        - Authorization:
            - productionefficiency
            - 'user.role:read'
  /delivery/statistics:
    get:
      summary: Доставка → Статистика
      operationId: get-delivery-statistics
      description: |
        Возвращает основные метрики по доставке за выбранный период по пиццериям (`units`).

        ### Расчет некоторых показателей:
        1. Процент доставки через курьерское приложение = `ordersWithCourierAppCount` / `deliveryOrdersCount`
        2. Количество заказов на курьера в час = `deliveryOrdersCount` / (`couriersShiftsDuration` / 3600)
        3. Загрузка кукрьеров = `tripsDuration` / `couriersShiftsDuration`

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        ### Исключенные данные:
        В ответ не попадают заказы с короткими поездками курьеров или быстрым приготовлением продуктов.
      x-internal: false
      security:
        - Authorization:
            - deliverystatistics
            - 'user.role:read'
      tags:
        - Доставка
  /delivery/vouchers:
    get:
      summary: Доставка → Сертификаты за опоздание
      operationId: get-delivery-vouchers
      description: |-
        Сертификаты за опоздание.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - deliverystatistics
            - 'user.role:read'
      tags:
        - Доставка
  /delivery/efficiency:
    get:
      summary: Доставка → Эффективность
      tags:
        - _in_development
      operationId: get-delivery-efficiency
      description: |-
        Возвращает метрики эффективности доставки за выбранный диапазон и по пиццериям (`units`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.
      security:
        - Authorization:
            - deliverystatistics
            - 'user.role:read'
  /delivery/couriers-orders:
    get:
      summary: Доставка → Заказы курьеров
      operationId: get-delivery-couriers-orders
      security:
        - Authorization:
            - deliverystatistics
            - 'user.role:read'
      description: |-
        Метрики по каждому заказу курьеров.

        Время в параметрах в возвращаемом ответе отдаётся по UTCefficiency

        Параметры `from` и `to` определяют фильтрация заказов по дате их создания и внесенных изменений.

        ### Требования к query параметрам:
        - `units` не может быть больше 30
        - `take` не может быть меньше 0 или больше 1000

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      tags:
        - Доставка
  /delivery/delivery-sectors:
    get:
      summary: Доставка → Сектора доставки
      operationId: get-delivery-sectors
      description: |-
        Возвращает данные о секторах доставки

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 отделов в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - deliverystatistics
            - 'user.role:read'
      tags:
        - Доставка
  /delivery/stop-sales-sectors:
    get:
      summary: Доставка → Стоп-продажи по секторам
      operationId: get-delivery-stop-sales-sectors
      description: |-
        Возвращает данные о стопах продаж за период для набора пиццерий (`units`).
        Стопы сгруппированы по пиццериям и секторам.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день;
        4. Начальная дата периода `to` - не раньше 1 апреля 2023 года.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - stopsales
            - 'user.role:read'
      tags:
        - Доставка
  /staff/members:
    get:
      summary: Команда → Список сотрудников
      operationId: get-staff-members
      description: |-
        Возвращает список сотрудников, отсортированный по дате трудоустройства (`hiredOn`).

        ### Требования к query параметрам:
        - фильтр по типу должности `staffType` применяется только по одному значению
        - фильтр по статусу `statuses` применяется по нескольким значениям (указывается через запятую без пробелов)
        - фильтр по дате трудоустройства `hiredFrom/hiredTo`, применяется как по промежутку дат, так и по отдельным from/to датам
        - фильтр по дате увольнения `dismissedFrom/dismissedTo`, применяется как по промежутку дат, так и по отдельным from/to датам
        - фильтр по дате изменения `lastModifiedFrom/lastModifiedTo`, применяется как по промежутку дат, так и по отдельным from/to датам
        - фильтр по заведениям `units` применяется по нескольким значениям; если не указан, то будут выданы записи по всем доступным для пользователя заведениям
        - фильтр `skip` должен быть больше 0, иначе возвращается 400
        - фильтр `take` должен быть больше 0 и меньше либо равен 1000, иначе возвращается 400
        - фильтр `hiredFrom` должен быть не больше `hiredTo`, иначе возвращается 400
        - фильтр `dismissedFrom` должен быть не больше `dismissedTo`, иначе возвращается 400
        - фильтр `lastModifiedFrom` должен быть не больше `lastModifiedTo`, иначе возвращается 400
        - разрешенные значения для фильтров `staffType`, `statuses` указаны в их описаниях

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'staffmembers:read'
            - 'user.role:read'
      tags:
        - Команда
  /staff/incentives/premium/one-time:
    post:
      summary: Команда → Премия единоразовая
      operationId: post-staff-incentives-premium-one-time
      security:
        - Authorization:
            - incentives
            - 'user.role:read'
      description: |-
        Метод позволяет назначить единоразовую премию сотруднику.

        ### Требования к query параметрам:
        1. Параметр `onLocal` может принимать дату и время в пределах текущего отчетного периода заведения, где работает сотрудник (по стандарту — до 5-го числа месяца, следующего за отчётным периодом). Например, если отчетный период для заведения закрывается 5-го числа, то:
           - если текущая дата ≤ 5-го числа, премии можно начислять, начиная с 1-го числа предыдущего месяца.
           - если текущая дата > 5-го числа, премии можно начислять, начиная с 1-го числа текущего месяца.
        2. Значение параметра `onLocal` не может быть позже текущего времени заведения, в котором работает сотрудник.

        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Division administrator` - Администратор подразделения
      tags:
        - Команда
  /staff/incentives/premium/hourly:
    post:
      summary: Команда → Премия к вознаграждению в час
      operationId: post-staff-incentives-premium-hourly
      security:
        - Authorization:
            - incentives
            - 'user.role:read'
      description: |-
        Метод позволяет назначить премию к вознаграждению за час на определённый промежуток времени сотруднику.

        ### Требования к query параметрам:
        1. Параметры `fromLocal` и `toLocal` могут принимать дату и время в пределах текущего отчетного периода заведения, где работает сотрудник (по стандарту — до 5-го числа месяца, следующего за отчётным периодом). Например, если отчетный период для заведения закрывается 5-го числа, то:
           - если текущая дата ≤ 5-го числа, премии можно начислять, начиная с 1-го числа предыдущего месяца.
           - если текущая дата > 5-го числа, премии можно начислять, начиная с 1-го числа текущего месяца.
        2. Значения параметров `fromLocal` и `toLocal` не могут быть позже текущего времени заведения, в котором работает сотрудник.

        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Division administrator` - Администратор подразделения
      tags:
        - Команда
  /staff/incentives/premium/position:
    post:
      summary: Команда → Премия по должности к вознаграждению в час
      operationId: post-staff-incentives-premium-position
      security:
        - Authorization:
            - incentives
            - 'user.role:read'
      description: |-
        Метод позволяет назначить премию к вознаграждению за час сотрудникам на определённых должностях в конкретном заведении на определённый промежуток времени.

        ### Требования к query параметрам:
        1. Параметры `fromLocal` и `toLocal` могут принимать дату и время в пределах текущего отчетного периода заведения, где работает сотрудник (по стандарту — до 5-го числа месяца, следующего за отчётным периодом). Например, если отчетный период для заведения закрывается 5-го числа, то:
           - если текущая дата ≤ 5-го числа, премии можно начислять, начиная с 1-го числа предыдущего месяца.
           - если текущая дата > 5-го числа, премии можно начислять, начиная с 1-го числа текущего месяца.
        2. Значения параметров `fromLocal` и `toLocal` не могут быть позже текущего времени заведения, в котором работает сотрудник.

        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Division administrator` - Администратор подразделения
      tags:
        - Команда
  /staff/incentives/premium:
    get:
      summary: Команда → Премии
      operationId: get-staff-incentives-premium
      security:
        - Authorization:
            - incentives
            - 'user.role:read'
      description: |-
        Метод позволяет получить список установленных премий сотрудникам в указанных заведениях за определённый период.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. В ответе будут отображены все премии, которые попадают в запрашиваемый период `from`-`to` полностью или частично.

        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Division administrator` - Администратор подразделения
      tags:
        - Команда
  /staff/members/search:
    get:
      summary: Команда → Поиск сотрудников
      operationId: get-staff-members-search
      description: |-
        Возвращает список сотрудников с данными о трудоустройстве.
        Для поиска используется алгоритм, который описан ниже, а результирующие персональные данные скрываются. 

        ### ВАЖНО: 
        Алгоритм рассматривает только указанные ниже группы совпадений!
        В результирующий список попадут все найденные записи, удовлетворяющие нижеперечисленным группам совпадения.

        ## Группировка запросов для алгоритма поиска

        ### 6 совпадений:

        Фамилия - Имя - Отчество - Номер телефона - Дата Рождения - ИНН

        ### 5 совпадений:

        Фамилия - Имя - Номер телефона - Дата Рождения - ИНН

        ### 4 совпадения:

        Фамилия - Имя - Номер телефона - Дата Рождения

        ### 3 совпадения:

        Фамилия - Имя - Номер телефона

        Фамилия - Имя - Дата Рождения

        Фамилия - Имя - ИНН

        ### 2 совпадения:

        Фамилия - Имя

        Фамилия - Номер телефона

        Фамилия - Дата рождения

        Фамилия - ИНН

        ### 1 совпадение:

        Номер телефона

        ИНН

        ### Требования к query параметрам:
        1. Если входные параметры поиска не попадают ни в одну из указанных групп, то вернется пустой результат
        2. Все совпадения, обнаруженные по указанным выше группам, будут включены в общий результат
        3. При передаче query-параметров в URL необходимо кодировать зарезервированные символы, такие как `+`, так как они могут интерпретироваться иначе. Например, если значение параметра `phoneNumber` начинается с `+`, как в `+79999999999`, то символ + должен быть закодирован как `%2B`. В результате значение должно выглядеть так: `%2B79999999999`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - staffmembersearch
            - 'user.role:read'
      tags:
        - Команда
  /staff/members/birthdays:
    get:
      summary: Команда → Поиск дней рождения сотрудников
      operationId: get-staff-members-birthdays
      description: Возвращает список дней рождения сотрудников во включающем диапазоне переданных дат
      security:
        - Authorization:
            - 'staffmembers:read'
            - 'user.role:read'
      tags:
        - Команда
  '/staff/members/{id}':
    get:
      summary: Команда → Информация о сотруднике
      operationId: get-staff-members-id
      description: |-
        Возвращает полную информацию по запрошенному сотруднику.

        Вы можете запросить информацию о сотруднике как по идентификатору сотрудника (`staffId`), так и по идентификатору пользователя (`userId`). Для этого необходимо указать дополнительный параметр `findby`. Данный параметр принимает 2 значения:
         - `staffid` - для поиска по идентификатору сотрудника (используется как стандартное значение)
         - `userid` - для поиска по идентификатору пользователя

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены.
        >
        >   `Employee` - Сотрудник. Получение данных **только о самом себе**
      security:
        - Authorization:
            - 'staffmembers:read'
            - 'user.role:read'
      tags:
        - Команда
  '/staff/members/{id}/suspend':
    post:
      summary: Команда → Отстранение сотрудника
      tags:
        - Команда
      operationId: post-staff-members-id-suspend
      description: |-
        Отстраняет сотрудника по id.

        Отстраненный сотрудник не участвует в штатной деятельности пиццерии:
         - выход на смены;
         - учет в штатных метриках пиццерии (текучесть, укомплектованность и т.д.).

        Отстранить можно только сотрудника, который сейчас находится в статусе Активен.

        Даты и время отстранения, передаваемые в API, ожидаются в UTC и далее будут приведены к локальным датам и времени относительно департамента отстраянемого сотрудника.

        Список идентификаторов причин для отстранения:
         - dc1746fb4916483797b16af1c8eae7a2 - просрочена мед. книжка;
         - 2206cdfd19564b1b9e52afded480d8c0 - отпуск;
         - c3e2ece1c8374e2681ba0750ca65dd82 - больничный;
         - 3f8481fdfa0a4be0b3c0a966c3ad0f39 - просрочено разрешение на работу или регистрация;
         - 64d65e1a72c1472c8a3175d0415e618f - другое.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'staffmembers:write'
            - 'user.role:read'
  /staff/members/directors:
    get:
      summary: Команда → Контакты руководителей
      operationId: get-staff-members-directors
      description: |
        Возвращает список руководителей доступных заведений.  
        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`). 
        ### Требования к query параметрам:
        1. Все параметры для запроса не являются обязательными к указанию;
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Если в запросе не будут указаны параметры `units` и `userId`, то будет возвращён общий список руководителей доступных заведений;
        4. Фильтр по типу руководителя `directorType` применяется только по одному значению.
        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'staffmembers:read'
            - 'user.role:read'
      tags:
        - Команда
  /staff/shifts:
    get:
      summary: Команда → Смены сотрудников (по пиццериям)
      operationId: get-staff-shifts
      security:
        - Authorization:
            - 'staffshifts:read'
            - 'user.role:read'
      description: |-
        Смены сотрудников (рабочее время, рабочие часы, фактические часы): отработанное время с детализацией по дневным, ночным и праздничным часам (в минутах), данные о доставленных заказах, расстоянии, стаже сотрудника на момент смены.

        Смены выбираются по времени начала. Также есть фильтр по типу сотрудника. Время смен не обрезается по фильтру. Если начало смены попало в диапазон `clockInFrom` – `clockInTo` (отметки времени начала смены), то смена вернётся целиком.
        Для получения всех часов по каждому сотруднику нужно выкачать все смены за период и сгруппировать у себя по staffId.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Команда
  /staff/members/shifts:
    get:
      summary: Команда → Смены сотрудников (по идентификаторам)
      operationId: get-staff-shifts-by-members
      security:
        - Authorization:
            - 'staffshifts:read'
            - 'user.role:read'
      description: |-
        Смены сотрудников (рабочее время, рабочие часы, фактические часы): отработанное время с детализацией по дневным, ночным и праздничным часам (в минутах), данные о доставленных заказах, расстоянии, стаже сотрудника на момент смены.

        Смены выбираются по времени начала. Также есть фильтр по типу сотрудника. Время смен не обрезается по фильтру. Если начало смены попало в диапазон `clockInFrom` – `clockInTo` (отметки времени начала смены), то смена вернётся целиком.
        Для получения всех часов по каждому сотруднику нужно выкачать все смены за период и сгруппировать у себя по staffId.


        ### Требования к query параметрам:
        1. В `staffIds` можно перечислить до 30 сотрудников в одном запросе;
        2. В `staffIds` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `clockInFrom` должен быть меньше, чем `clockInTo`;


        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Команда
  /staff/shifts/clock-out:
    post:
      summary: Команда → Закрытие смены
      operationId: post-staff-shifts-clock-out
      description: |-
        Закрытие активной смены сотрудника.

        <!-- theme: none -->

        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
        >
        >   `Division administrator` - Администратор подразделения
      security:
        - Authorization:
            - 'staffshifts:write'
            - 'user.role:read'
      tags:
        - Команда
  /staff/couriers-on-shift:
    get:
      summary: Команда → Курьеры на смене
      operationId: get-staff-members-curiers-on-shift
      description: |-
        Возвращает список курьеров на смене на момент отправки запроса.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Дата `on` должна быть в прошлом. 

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'staffshifts:read'
            - 'user.role:read'
      tags:
        - Команда
  /staff/schedules:
    get:
      summary: Команда → Расписания
      operationId: get-staff-schedules
      description: |-
        Расписания смен сотрудников

        Период выборки учитывает только начало смены в расписании, то есть конец смены может выходить за пределы периода выборки. 

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'staffshifts:read'
            - 'user.role:read'
      tags:
        - Команда
    post:
      summary: Команда → Расписания (создание)
      operationId: post-staff-schedules
      description: |-
        Создание расписания смен сотрудников.

        ### Требования к входным параметрам:
         - При добавлении нескольких смен на одного сотрудника они не должны пересекаться.
         - scheduledShiftStartAt и scheduledShiftEndAt необходимо передавать в UTC. Однако при получении графика будет отображаться уже локальное время.
         - scheduledShiftStartAt, scheduledShiftEndAt - должны быть переданы в разрезе 15-ти минутного интервала без секунд.
         - Максимальная длительность смены в графике 24 часа, минимальная 15 минут.
         - Добавлять смены в график можно не дальше чем на 31 день.
         - Добавлять смены в график можно только в будущем.
         - Запрещено добавлять курьеров производственные станции внутри заведения.
         - Запрещено добавлять работника заведения в график курьеров.
         - Список доступных производственных станций можно запросить в `Заведения → Производственные станции`
         - Список доступных должностей можно запросить в `Команда → Должности сотрудников`

        ---

         ### Требования к пользовательскому доступу:
         Требуется одна из ролей:
          - `Division administrator` - Администратор подразделения
          - `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'staffshifts:write'
            - 'user.role:read'
      tags:
        - Команда
  '/staff/schedules/{id}':
    delete:
      summary: Команда → Расписания (удаление)
      operationId: delete-staff-schedules
      description: |-
        Удаление расписания смен сотрудников.

        ### Требования к удаляемой запланированной смене:
        - Должен быть доступ к заведению, в графике которого находится запланированная смена
        - Нельзя удалять запланированные смены из закрытых заведений
        - Нельзя удалять запланированные смены в прошлом

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'staffshifts:write'
            - 'user.role:read'
      tags:
        - Команда
  /staff/schedules/forecast:
    get:
      summary: 'Команда → Расписания: прогнозные метрики'
      operationId: get-staff-schedules-forecast
      description: |-
        Возвращает прогнозные метрики расписания сотрудников (графики) по заведениям на указанную дату, включая прогноз выручки, количества заказов и товаров, рекомендуемую и запланированную нагрузку сотрудников, а также почасовой прогноз по заведению и курьерам.
        Метрики строятся только для заведений (UnitType = Store).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `units` должен содержать UUID-ы заведений (тип заведения Store) (пиццерии/кофейни). Если запрос будет содержать . 

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'staffshifts:read'
            - 'user.role:read'
      tags:
        - Команда
  /staff/positions:
    get:
      summary: Команда → Должности сотрудников
      operationId: get-staff-positions
      description: Полный список активных должностей сотрудников в системе.
      security:
        - Authorization:
            - shared
      tags:
        - Команда
  /staff/positions/history:
    get:
      summary: Команда → История должностей сотрудников
      operationId: get-staff-positions-history
      security:
        - Authorization:
            - shared
      description: |-
        ### Требования к входным параметрам:
         - В units можно перечислить до 5 заведений в одном запросе;
         - В units следует перечислять UUID-ы строго через запятую без пробелов;
         - В staffMembers ожно перечислить до 30 сотрудников в одном запросе;
         - В staffMembers следует перечислять UUID-ы строго через запятую без пробелов;
         - В запросе необходимо передать один из параметров: `units` или `staffMembers`


        > #### Доступно для следующих ролей:
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Employee` - Сотрудник. Получение данных **только о самом себе**
      tags:
        - Команда
  /staff/schedules/availability-periods:
    get:
      summary: Команда → Карта возможностей
      operationId: get-schedule-availability-periods
      description: |-
        Получение карты возможностей сотрудников в заведении.

        ### Требования к входным параметрам:
         - В units можно перечислить до 5 заведений в одном запросе;
         - В units следует перечислять UUID-ы строго через запятую без пробелов;
         - В staffMembers ожно перечислить до 30 сотрудников в одном запросе;
         - В staffMembers следует перечислять UUID-ы строго через запятую без пробелов;
         - В запросе необходимо передать один из параметров: `units` или `staffMembers`
         - Максимальный диапазон выборки - 14 дней.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
        >
        >   `Employee` - Сотрудник. Получение данных **только о самом себе**
      security:
        - Authorization:
            - 'staffmembers:read'
            - 'user.role:read'
      tags:
        - Команда
  /staff/incentives-by-members:
    get:
      summary: Команда → Вознаграждения (новое)
      operationId: get-staff-incentives-by-members
      description: |-
        Возвращает вознаграждения за период для набора заведений (`units`).
        Вознаграждения сгруппированы по сотруднику с детализацией: смены, премии.
        Вознаграждения считаются для сотрудников, которые отработали хотя бы одну смену в указанных заведения за указанный период времени, а также сведения о премии.

        Из-за возможного изменения ставки и коэффициентов в течение времени смены, она разбивается на интервалы по 15 минут. Затем к каждому интервалу применяются все коэффициенты и ставки. Остаток от разбиения не учитывается. Например, смена длительностью 65 минут будет разбита на 4 интервала и 5 оставшихся минут не будут учитываться.

        Примеры:

        *Пример 1: Инструктор отработал смену с 08:00 до 16:00. Его ставка 150 рублей/час. В итоге он получит вознаграждение: 8 × 150 = 1200 рублей.*

        *Пример 2: Стажер отработал вечернюю смену с 16:00 до 00:00. С 22:00 установлен ночной коэффициент — 2. Ставка сотрудника 60 рублей/час. За смену он получит вознаграждение: 6 × 60 + 2 × 2 × 60 = 360 + 240 = 600 рублей.*

        *Пример 3: Пиццамейкер работал с 08:00 до 14:00. Его ставка 100 рублей/час. С 08:00 до 12:00 ожидался огромный наплыв посетителей, поэтому за работу в это время установлен коэффициент особого дня — 1,5. Сотрудник получит такое вознаграждение: 4 × 1,5 × 100 +2 × 100 = 600 + 200 = 800 рублей.*

        *Пример 4: Кандидат отработал 4 часа. Его ставка 70 рублей в час + премия за стаж 15 рублей за час. Он получит вознаграждение: (70 + 15) × 4 = 340 рублей.*

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день;
        4. Фильтр по типу должности `staffTypes` применяется по одному или нескольким типам. В `staffTypes` следует перечислять типы должностей строго через запятую без пробелов.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - incentives
            - 'user.role:read'
      tags:
        - Команда
  /staff/vacancies/count:
    get:
      summary: Команда → Количество открытых вакансий
      operationId: get-applicants-vacancies-count
      security:
        - Authorization:
            - shared
      description: |-
        Получение количества открытых вакансий в заведениях

        ### Требования к входным параметрам:
         - В `units` можно перечислить до 30 заведений в одном запросе;
         - В `units` следует перечислять UUID-ы строго через запятую без пробелов;
         - В `localities` можно перечислить до 30 населенных пунктов в одном запросе;
         - В `localities` следует перечислять UUID-ы строго через запятую без пробелов;
         - Можно передавать либо параметр `units` для получения вакансий по переданным заведениям либо параметр `localities` для получения вакансий по всем заведениям переданных населенных пунктов;
         - Если не передать ни `units` ни `localities` будут выданы все вакансии по всем заведениям;
         - Можно получить информацию только о вакансиях в Заведениях (пиццериях/кофейнях) и ПРЦ (Производственно-распределительный центр);
         - Параметр `countryId` **пока** не обязательный к указаню; нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2;
         - Параметр  `businessId` **пока** не обязательный к указаню; нужно передавать идентификатор бизнеса в UUID-формате (для Пиццы это значение `63d4829611ea45c8ae71394860a2481c`, для Дринкит — `c0b18e725258427a8bffea4f73957b0e`)
      tags:
        - Команда
      deprecated: true
  /staff/vacancies:
    get:
      summary: Команда → Открытые вакансии
      operationId: get-applicants-vacancies
      security:
        - Authorization:
            - shared
      description: |-
        Получение открытых вакансий в заведениях

        ### Требования к входным параметрам:
         - В `units` можно перечислить до 30 заведений в одном запросе;
         - В `units` следует перечислять UUID-ы строго через запятую без пробелов;
         - В `localities` можно перечислить до 30 населенных пунктов в одном запросе;
         - В `localities` следует перечислять UUID-ы строго через запятую без пробелов;
         - Можно передавать либо параметр `units` для получения вакансий по переданным заведениям либо параметр `localities` для получения вакансий по всем заведениям переданных населенных пунктов;
         - Если не передать ни `units`, ни `localities`, будут выданы все вакансии по всем заведениям;
         - Фильтр по типу должности `staffTypes` применяется по одному или нескольким типам. В `staffTypes` следует перечислять типы должностей строго через запятую без пробелов;
          - Можно получить информацию только о вакансиях в Заведениях (пиццериях/кофейнях) и ПРЦ (Производственно-распределительный центр);
          - Параметр `countryId` **пока** не обязательный к указаню; нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2;
          - Параметр  `businessId` **пока** не обязательный к указаню; нужно передавать идентификатор бизнеса в UUID-формате (для Пиццы это значение `63d4829611ea45c8ae71394860a2481c`, для Дринкит — `c0b18e725258427a8bffea4f73957b0e`)
      tags:
        - Команда
  /organization-structure/legal-entities:
    get:
      summary: Оргструктура → Список юрлиц
      operationId: get-legal-entities
      description: |-
        Возвращает список юрлиц, отсортированный по ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        <b>ВНИМАНИЕ:</b> параметры `takenCount` и `totalCount` скоро будут удалены!
      security:
        - Authorization:
            - organizationstructure
      tags:
        - Оргструктура
  /organization-structure/legal-entity-types:
    get:
      summary: Оргструктура → Список типов юрлиц
      operationId: get-legal-entity-types
      description: 'Возвращает список типов юрлиц (ООО, ИП, и т.д.), отсортированный по ID.'
      security:
        - Authorization:
            - organizationstructure
      tags:
        - Оргструктура
  /organization-structure/localities:
    get:
      summary: Оргструктура → Список населённых пунктов
      operationId: get-localities
      description: |
        Возвращает список публичных населённых пунктов, в которых есть подразделения со статусом «Открыто» или «Скоро открытие», отсортированный по наименованию населённого пункта.

        ### Требования к query параметрам:
        1. Параметр `countryId` является обязательным;
        2. В `countryId` нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2.

        >  **Доступно** по запросу в `support`. Данный запрос может быть удалён в любой момент.
      security:
        - Authorization:
            - 'localities:read'
      deprecated: true
      tags:
        - Оргструктура
  /accounting/suppliers:
    get:
      summary: Учет → Список поставщиков
      operationId: get-suppliers
      description: |-
        Возвращает список поставщиков, отсортированный ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/dough-consumption:
    get:
      summary: Учет → Расход теста
      operationId: get-dough-consumption
      description: |-
        Позволяет получить расход теста по часам.

        В ответе будут включены только те промежутки, в которых происходил расход теста. Так например если заведение работает с 09:00 - 23:00, то в ответе будут только промежутки между 09:00 - 23:00. Любой отсутствующий промежуток можно считать за 0.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. Диапазон дат между `toDate` и `fromDate` параметрами не должен превышать 31 день.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/local-suppliers:
    get:
      summary: Учет → Список локальных поставщиков
      operationId: get-local-suppliers
      description: |-
        Возвращает список локальных поставщиков, отсортированный по ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/products:
    get:
      summary: Учёт → Продукты
      operationId: get-products
      description: |-
        Возвращает список продуктов, отсортированный по ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        <b>ВНИМАНИЕ:</b> параметры `takenCount` и `totalCount` скоро будут удалены!
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  '/accounting/products/{id}':
    get:
      summary: Учёт → Информация о продукте
      operationId: get-products-id
      description: Возвращает информацию о продукте
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/stock-items:
    get:
      summary: Учёт → Сырьё
      operationId: get-stock-items
      description: |-
        ⚠️ **DEPRECATED** - данный endpoint устарел. Пожалуйста, используйте новый Accounting API [**Справочники → Сырьё**](https://docs.dodois.io/docs/accounting/3fe4c4a59cf7e-spravochniki-syryo)

        Возвращает список сырья, отсортированный по ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).
      deprecated: true
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/local-stock-items:
    get:
      summary: Учёт → Локальное сырьё
      operationId: get-local-stock-items
      description: |-
        ⚠️ **DEPRECATED** - данный endpoint устарел. Пожалуйста, используйте новый Accounting API [**Справочники → Сырьё**](https://docs.dodois.io/docs/accounting/3fe4c4a59cf7e-spravochniki-syryo)

        Возвращает список локального сырья, отсортированный по ID.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      deprecated: true
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/semi-finished-products-production:
    get:
      summary: Учёт → Произведенные полуфабрикаты
      operationId: get-semi-finished-products-production
      description: |-
        Возвращает полуфабрикаты, произведенные в указанный период (включительно).

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса

        > **Изменение в расчёте цен с 9 февраля 2026 года**. Теперь вместо цен, рассчитанных на уровне подразделения, 
        > API возвращает цены на уровне ресторана (в исторических данных тоже).
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/write-offs/products:
    get:
      summary: Учёт → Списанные продукты
      operationId: get-write-off-products
      description: |-
        Возвращает списанные продукты за указанный период (включительно), отсортированные по дате списания.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/write-offs:
    post:
      summary: Учёт → Списание
      operationId: post-accounting-write-offs-products
      description: |-
        Метод позволяет создать списание продукта или сырья.

        ### Требования к входным параметрам:
        - В одном запросе можно передать до 10 записей.
        - Для каждой операции списания необходимо указать либо идентификатор продукта (`productId`), либо идентификатор сырья (`stockItemId`).
        - Параметр `measurementUnit` должен соответствовать единице измерения указанного продукта или сырья.
        - Если вы списываете продукт, в `measurementUnit` следует указывать значение `Quantity`.
        - Для `measurementUnit` со значениями `Quantity` и `Meter`, значение `quantity` должно быть целым числом.
        - Для `measurementUnit` со значениями `Kilogram` и `Liter`, значение `quantity` может быть дробным числом с точностью до трех знаков после запятой (например, до граммов или миллилитров).
        - Максимальная длинна `comment` 255 символов.
        - Причина списания (`reason`) должна быть разрешена для указанного заведения (`unitId`). Доступность причин может отличаться для разных заведений.
         
        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Учет
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
  /accounting/write-offs/stock-items:
    get:
      summary: Учёт → Списанное сырье
      operationId: get-write-offs-stock-items
      description: |-
        Возвращает списанное сырье за указанный период (включительно), отсортированное по дате списания.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/defective-products:
    get:
      summary: Учёт → Забракованные продукты
      operationId: get-defective-products
      description: |-
        Возвращает забракованные продукты за указанный период (включительно), отсортированные по дате и идентификатору продажи.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/staff-meals:
    get:
      summary: Учёт → Питание команды
      operationId: get-staff-meals
      description: |-
        Возвращает продукты за указанный период (включительно), израсходованные на питание команды, отсортированные по дате принятия заказа и идентификатору продажи.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/cancelled-sales:
    get:
      summary: Учёт → Отмены заказов
      operationId: get-cancelled-sales
      description: |-
        Возвращает продукты за указанный период (включительно), израсходованные на отмены заказов, отсортированные по дате, идентификатору продажи и идентификатору записи.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`.
        4. Максимальный период запроса - 32 дня
        5. Максимальное количество записей в одном запросе `take` - 1000

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/sales:
    get:
      summary: Учёт → Продажи
      operationId: get-sales
      description: |-
        Возвращает продажи за указанный период (включительно), отсортированные по дате и идентификатору продажи.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`;
        4. Диапазон дат между `to` и `from` параметрами не должен превышать 31 день.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - sales
            - 'user.role:read'
      tags:
        - Учет
  /accounting/stock-consumptions-by-period:
    get:
      summary: Учёт → Расход сырья за период
      operationId: get-stock-consumptions-by-period
      description: |-
        Возвращает расход сырья за указанный период (включительно), сгруппированный по идентификатору заведения, идентификатору сырья, типу расхода и единице измерения и отсортированный по идентификатору заведения, типу расхода и идентификатору сырья.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        Данные в ответе API могут отличаться от аналогиченого отчета в Dodo IS. Данное API возвращает только данные о расходе сырья и не учитывает перемещение.

        Параметры `costWithVat` и `costWithoutVat` расчитываются исходя из цены сырья на конец запрашивамого периода. Т.е. запросив данные за 30 дней, общая сумма будет равна кол-ву сырья умноженного на цену сырья в 30й день.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`;
        4. Максимальный период запроса - 32 дня
        5. Максимальное количество записей в одном запросе `take` - 1000

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса

        > **Изменение в расчёте цен с 9 февраля 2026 года**. Теперь вместо цен, рассчитанных на уровне подразделения, 
        > API возвращает цены на уровне ресторана (в исторических данных тоже).
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/stock-transfers:
    get:
      summary: Учёт → Перемещения сырья
      operationId: get-stock-transfers
      description: |-
        Возвращает список перемещений сырья за указанный период (включительно), отсортированный по дате создания перемещения.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `shippedFrom` должен быть меньше `shippedTo`;
        4. `receivedFrom` должен быть меньше `receivedTo`;
        5. `createdFrom` должен быть меньше `createdTo`;
        6. В `statuses` следует перечислять статусы перемещений через запятую без пробелов;

        Статусы перемещений:
        <code>
        Created: 1 (Новая заявка на перемещение)
        Ordered:2 (Заказанная заявка на перемещение)
        Shipped: 3 (Отгруженная заявка на перемещение)
        Received: 4 (Полученная заявка на перемещение)
        Cancelled: 5 (Отмененная заявка на перемещение)
        </code>

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/incoming-stock-items:
    get:
      deprecated: true
      summary: Учёт → Приходы сырья
      operationId: get-incoming-stock-items
      description: |-
        ⚠️ **DEPRECATED** - Пожалуйста, используйте  [новый Accounting API](https://docs.dodois.io/docs/accounting/62c1e14c070bb-postavki-prihody-syrya)

        Возвращает список приходов за указанный период (включительно), отсортированный по дате получения и идентификатору записи.

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/incoming-stock-items/by-supply:
    get:
      deprecated: true
      summary: Учёт → Приходы сырья по поставке
      operationId: get-incoming-stock-items-by-supply
      description: |-
        ⚠️ **DEPRECATED** - Пожалуйста, используйте  [новый Accounting API](https://docs.dodois.io/docs/accounting/62c1e14c070bb-postavki-prihody-syrya)

        Возвращает список приходов за указанный период (включительно), сгруппированный по накладной и отсортированный по дате получения и идентификатору записи.
        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).
        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`;
        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      tags:
        - Учет
  /accounting/inventory-stocks:
    get:
      summary: Учёт → Складские остатки
      operationId: get-accounting-inventory-stocks
      security:
        - Authorization:
            - 'accounting:read'
            - 'user.role:read'
      description: |-
        Возвращает складские остатки.

        По умолчанию возвращаются только позиции, подтверждённые ревизией (`isConfirmed = true`).
        Передав `includeUnconfirmed=true`, можно также получить расчётные остатки, по которым ревизия ещё не проводилась (`isConfirmed = false`).

        Сырьё не возвращается в ответе, если выполняется хотя бы одно из условий:
        - не было ни ревизий, ни расчётных остатков за последние 60 дней;
        - расчёт остатков не выполнялся в течение последних 90 минут.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. В `stockItems` следует перечислять UUID-ы строго через запятую без пробелов;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса

        > **Изменение в расчёте цен с 9 февраля 2026 года**. Теперь вместо цен, рассчитанных на уровне подразделения, 
        > API возвращает цены на уровне ресторана (в исторических данных тоже).
      tags:
        - Учет
  /supplies/receipts:
    post:
      deprecated: true
      summary: Поставки → Поступление
      operationId: post-supply
      security:
        - Authorization:
            - 'receipts:write'
            - 'user.role:read'
      description: |-
        ⚠️ **DEPRECATED** - Пожалуйста, используйте  [новый Accounting API](https://docs.dodois.io/docs/accounting/b76b1c257859d-postavki-postuplenie-syrya)

        Позволяет оформить поставку сырья поставщиком.


         ### Требования к пользовательскому доступу:
         Требуется одна из ролей:
          - `Division administrator` - Администратор подразделения
          - `Store Manager` - Менеджер офиса
          - `Shift supervisor` - Менеджер смены
      tags:
        - Поставки
  /units/shifts:
    get:
      summary: Заведения → Смены заведений
      operationId: get-unit-shifts
      description: |-
        Возвращает список смен заведений, отсортированный по дате начала смены. Смены выбираются по времени начала (eсли начало смены попало в диапазон from – to включительно). 

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
        3. `from` должен быть меньше, чем `to`;

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
      security:
        - Authorization:
            - 'unitshifts:read'
            - 'unit:read'
            - 'user.role:read'
      tags:
        - Заведения
  /units:
    get:
      summary: Заведения → Информация о заведениях
      operationId: get-all-units
      description: |
        Возвращает список заведений с основной информацией о них. 

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `countryId` нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2;
        2. В `businessId` нужно передавать идентификатор бизнеса в UUID-формате (для Пиццы это значение `63d4829611ea45c8ae71394860a2481c`, для Дринкит — `c0b18e725258427a8bffea4f73957b0e`);
        3. Параметры `countryId` и `businessId` являются обязательными;
        4. Параметр `unitStates` является необязательным. Если ничего не передавать в этот параметр, то будет возвращён неотфильтрованный по статусу заведения список;
        5. Параметр `unitTypes` является необязательным. Если ничего не передавать в этот параметр, то будет возвращён неотфильтрованный по типу заведения список.
      security:
        - Authorization:
            - shared
      tags:
        - Заведения
  /units/stores:
    get:
      summary: Заведения → Информация о пиццериях/кофейнях
      operationId: get-all-stores
      description: |
        Возвращает список пиццерий/кофеен с информацией о них. 

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `countryId` нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2;
        2. В `businessId` нужно передавать идентификатор бизнеса в UUID-формате (для Пиццы это значение `63d4829611ea45c8ae71394860a2481c`, для Дринкит — `c0b18e725258427a8bffea4f73957b0e`);
        3. Параметры `countryId` и `businessId` являются обязательными;
        4. Параметр `organizations` является необязательным. В `organizations` можно перечислить до 30 организаций в одном запросе. В `organizations` следует перечислять UUID-ы строго через запятую без пробелов;
        5. Параметр `unitStates` является необязательным. Если ничего не передавать в этот параметр, то будет возвращён неотфильтрованный по статусу заведения список.
      security:
        - Authorization:
            - shared
      tags:
        - Заведения
  /units/distributioncenters:
    get:
      summary: Заведения → Информация о ПРЦ
      operationId: get-all-distributioncenters
      description: |
        Возвращает список ПРЦ (производственно-распределительный центр) с информацией о них. 

        Для получения данных необходимо указывать параметр `skip`, смещая его на количество уже полученных записей. Повторять до тех пор, пока не будет достигнут конец списка (`isEndOfListReached = true`).

        ### Требования к query параметрам:
        1. В `countryId` нужно передавать идентификатор страны в формате ISO 3166-1 alpha-2;
        2. В `businessId` нужно передавать идентификатор бизнеса в UUID-формате (для Пиццы это значение `63d4829611ea45c8ae71394860a2481c`, для Дринкит — `c0b18e725258427a8bffea4f73957b0e`);
        3. Параметры `countryId` и `businessId` являются обязательными;
        4. Параметр `unitStates` является необязательным. Если ничего не передавать в этот параметр, то будет возвращён неотфильтрованный по статусу ПРЦ список.
      security:
        - Authorization:
            - shared
      tags:
        - Заведения
  /units/work-stations:
    get:
      summary: Заведения → Производственные станции
      operationId: get-units-work-stations
      description: |
        Возвращает список производственных подстанций.

        ### Требования к query параметрам:
        1. В `units` можно перечислить до 30 заведений в одном запросе;
        2. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      security:
        - Authorization:
            - shared
            - 'unit:read'
            - 'user.role:read'
      tags:
        - Заведения
  /units/month-goals:
    get:
      summary: Заведения → Цели на месяц
      operationId: get-units-month-goals
      description: |-
        Возвращает цели пиццерии на месяц.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >    
        >   `Shift supervisor` - Менеджер смены
      security:
        - Authorization:
            - 'unit:read'
            - 'user.role:read'
      tags:
        - Заведения
    patch:
      summary: Заведения → Цели на месяц
      operationId: patch-units-month-goals
      description: |-
        Изменение цель пиццерии на месяц.

        ### Требования к query параметрам:
        1. Нельзя изменить цель пиццерии в прошлом.
        2. Если не передать какой-либо из параметров или передать null, то изменение для данного парметра не применится. Позволяет точечно изменять только 1 из параметров.

        > #### Доступно для следующих ролей:
        >
        >   `Division administrator` - Администратор подразделения
        >
        >   `Store Manager` - Менеджер офиса
        >    
        >   `Shift supervisor` - Менеджер смены
      tags:
        - Заведения
      security:
        - Authorization:
            - 'unit:write'
            - 'user.role:read'
  /finances/sales/country/daily:
    get:
      summary: Финансы → Дневные продажи по стране
      operationId: get-finances-sales-daily
      tags:
        - Финансы
      description: |-
        Возвращает дневные данные продаж по стране за указанный период.
        Данные продаж агрегированы по дням и разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `fromDate` должен быть меньше, чем `toDate`.
        2. Левая граница `fromDate` и правая граница `toDate` - включающие.
        3. Максимальный период запроса - 10 дней
      security:
        - Authorization:
            - shared
  /finances/sales/units/daily:
    get:
      summary: Финансы → Дневные продажи по заведениям
      operationId: get-finances-sales-daily-units
      tags:
        - Финансы
      description: |-
        Возвращает дневные данные продаж по заведениям за указанный период.
        Данные продаж агрегированы по дням и разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `fromDate` должен быть меньше, чем `toDate`.
        2. Левая граница `fromDate` и правая граница `toDate` - включающие.
        3. Максимальный период запроса - 10 дней
        4. В `units` можно перечислить до 30 заведений в одном запросе;
        5. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      security:
        - Authorization:
            - shared
  /finances/sales/country/monthly:
    get:
      summary: Финансы → Месячные продажи по стране
      operationId: get-finances-sales-monthly
      tags:
        - Финансы
      description: |-
        Возвращает месячные данные продаж по стране за указанный период.
        Данные продаж агрегированы по месяцам и разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `fromDate` должен быть меньше, чем `toDate`.
        2. Левая граница `fromDate` и правая граница `toDate` - включающие.
        3. Максимальный период запроса - 62 дня
      security:
        - Authorization:
            - shared
  /finances/sales/units/monthly:
    get:
      summary: Финансы → Месячные продажи по заведениям
      operationId: get-finances-sales-monthly-units
      tags:
        - Финансы
      description: |-
        Возвращает месячные данные продаж по заведениям за указанный период.
        Данные продаж агрегированы по месяцам и разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `fromDate` должен быть меньше, чем `toDate`.
        2. Левая граница `fromDate` и правая граница `toDate` - включающие.
        3. Максимальный период запроса - 62 дня
        4. В `units` можно перечислить до 30 заведений в одном запросе;
        5. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      security:
        - Authorization:
            - shared
  /finances/sales/country:
    get:
      summary: Финансы → Продажи по стране за период
      operationId: get-finances-sales-period
      tags:
        - Финансы
      description: |
        Возвращает данные продаж по стране за указанный период.
        Данные продаж разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `from` должен быть меньше, чем `to`.
        2. Левая граница `from` - включающая, правая `to` - исключающая
        3. Максимальный период запроса - 62 дня
      security:
        - Authorization:
            - shared
  /finances/sales/units:
    get:
      summary: Финансы → Продажи по заведениям за период
      operationId: get-finances-sales-period-units
      tags:
        - Финансы
      description: |-
        Возвращает данные продаж по заведениям за указанный период.
        Данные продаж агрегированы по месяцам и разбиты по каналам продаж, источникам заказа и методам оплаты.

        В данных продаж учитываются и возвращаются только заказы с перечисленными условиями:
        - Допустимые каналы продаж: Delivery, Dine-in, Takeaway
        - Допустимые источники заказов: CallCenter, Website, Dine-in, MobileApp, Manager, Aggregator, Kiosk, ChatBot
        - Допустимые виды платежей: Online, Cash, Card, Aggregator
        - Не учитываются заказы, которые созданы как замена бракованных заказов
        - Источник заказа Dine-in или Manager - это вероятнее всего будет касса ресторана.
        - В ответе возвращаются только ненулевые значения по комбинациям каналов продаж, источников заказов и видов платежей

        ### Требования к query параметрам:
        1. `fromDate` должен быть меньше, чем `toDate`.
        2. Левая граница `from` - включающая, правая `to` - исключающая
        3. Максимальный период запроса - 62 дня
        4. В `units` можно перечислить до 30 заведений в одном запросе;
        5. В `units` следует перечислять UUID-ы строго через запятую без пробелов;
      security:
        - Authorization:
            - shared
components:
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://auth.dodois.io/connect/authorize'
          tokenUrl: 'https://auth.dodois.io/connect/token'
          refreshUrl: 'https://auth.dodois.io/connect/token'
          scopes:
            shared: общее
            orders: Заказы
            accounting: 'Учет, общий доступ (obsolete, наследуемая область для совместимости)'
            'accounting:read': 'Учет, доступ на чтение'
            deliverystatistics: Статистика доставки
            incentives: Вознаграждения сотруников
            offline_access: Получение refresh_token
            organizationstructure: Оргструктура
            'localities:read': 'Населённые пункты, доступ на чтение'
            productionefficiency: Эффективность производства
            sales: Продажи
            'staffshifts:read': 'Смены сотрудников / команды, доступ на чтение'
            'staffshifts:write': 'Смены сотрудников / команды, доступ на запись'
            'staffmembers:read': 'Сотрудники / команда, доступ на чтение (содержит персональные данные)'
            'staffmembers:write': 'Сотрудники / команда, доступ на запись'
            stopsales: Стоп-продажи
            'unitshifts:read': 'Смены заведений, доступ на чтение'
            staffmembersearch: Поиск сотрудников
            'receipts:write': Оформление поставок
            'unit:read': 'Заведения, доступ на чтение'
            'unit:write': 'Заведения, доступ на запись'
            'user.role:read': Роли и юниты пользователя
      description: ''
tags:
  - name: Доставка
  - name: Заказы
  - name: Заведения
  - name: Команда
  - name: Оргструктура
  - name: Поставки
  - name: Производство
  - name: Учет
  - name: Финансы
  - name: _in_development
